#!/bin/bash

# Teclado
    riverctl keyboard-layout br
    riverctl set-repeat 50 300

# Executar ao iniciar
riverctl spawn waybar
riverctl spawn "swaybg -i ~/.config/river/wallpaper.jpg"

# Binds
    # Aplicativos
    riverctl map normal Super Return spawn foot
    riverctl map normal Super W spawn firefox
    riverctl map normal Super R spawn "wofi --show drun"

    # Screenshots
    riverctl map normal None Print spawn 'grim -g "$(slurp)" - | wl-copy -t image/png'
    riverctl map normal Super Print spawn ~/.config/river/screenshot

    # Cmus
        # Pausar
        riverctl map normal Super C spawn "cmus-remote -u" 

        # Pular
        riverctl map normal Super B spawn "cmus-remote -n"

        # Voltar
        riverctl map normal Super Z spawn "cmus-remote -r"

    # Outros
    riverctl map normal Super Backspace close
    riverctl map normal Super F toggle-fullscreen

    # Fechar River
    riverctl map normal Super+Shift Backspace exit

# Tags
    # Tags gerais
    for i in $(seq 1 9)
    do
        tags=$((1 << ($i - 1)))
    
        # Mudar a tag focada
        riverctl map normal Super $i set-focused-tags $tags
    
        # Mover as tags
        riverctl map normal Super+Shift $i set-view-tags $tags
    done

    # Tags focadas
        # Mudar a tag focada
        riverctl map normal Super J focus-view next
        riverctl map normal Super K focus-view previous
        
        # Mover as tags
        riverctl map normal Super+Shift J swap next
        riverctl map normal Super+Shift K swap previous

    # Cor da borda
    riverctl border-color-focused 0x93a1a1
    riverctl border-color-unfocused 0x586e75

    # Layout e gaps
    riverctl default-layout rivertile
    rivertile -view-padding 3 -outer-padding 3 &

# Outros
    # Make all views with an app-id that starts with "float" and title "foo" start floating.
    riverctl rule-add -app-id 'float*' -title 'foo' float
    
    # Make all views with app-id "bar" and any title use client-side decorations
    riverctl rule-add -app-id "bar" csd
